---
- hosts: localhost
  # run this task in the host
  connection: local
  vars:
    lxd_endpoint: https://octo1.lan:8443
  tasks:
    - name: create containers
      loop: "{{ groups['all'] }}"
      lxd_container:
        name: "{{ item }}"
        state: started
        source:
          type: image
          mode: pull
          server: https://images.linuxcontainers.org
          alias: ubuntu/xenial/amd64
        profiles: [lan,docker]
        url: "{{ lxd_endpoint }}"
