name: base
description: |
  launch host with ability to be managed by ansible
config:
  security.nesting: "true"
  security.privileged: "no"
  user.user-data: |
    #cloud-config
    package_update: true
    packages:
    - python
